build: false

platform: x86

clone_folder: c:\projects\paroki\development

services:
  - postgresql

cache:
  - '%LOCALAPPDATA%\Composer\files'
  - '%APPVEYOR_BUILD_FOLDER%\node_modules'
  - .cache/yarn

init:
  - SET PATH=c:\tools\php72;%PATH%

environment:
    APP_ENV: 'test'
    nodejs_version: "8"

install:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - SET DATABASE_URL=postgres://postgres:Password12!@localhost/paroki
  - ps: Install-Product node $env:nodejs_version
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst -y php
  - cd c:\tools\php72
  - copy php.ini-production php.ini /Y
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_pdo_sqlite.dll >> php.ini
  - echo extension=php_pdo_pgsql.dll >> php.ini
  - echo memory_limit=1G >> php.ini
  - cd %APPVEYOR_BUILD_FOLDER%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --no-interaction --no-progress --ignore-platform-reqs
  - php vendor\symfony\phpunit-bridge\bin\simple-phpunit install

before_test:
  - node --version
  - cd %APPVEYOR_BUILD_FOLDER%
  - php bin/console doctrine:database:create -n --if-not-exists
  - php bin/console doctrine:schema:create -n
  - yarn --cache-folder=.cache/yarn --no-progress
  - yarn build

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - php vendor\phpspec\phpspec\bin\phpspec run
  - php vendor\behat\behat\bin\behat --format=progress
  - php vendor\symfony\phpunit-bridge\bin\simple-phpunit
  - yarn test
