build: false

platform: x86

clone_folder: c:\projects\paroki\development

services:
  - postgresql101

cache:
  - '%LOCALAPPDATA%\Composer\files'

init:
  - SET PATH=c:\tools\php72;%PATH%

environment:
    APP_ENV: 'test'

install:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - SET DATABASE_URL=postgres://postgres:Password12@localhost/paroki
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst -y php
  - cd c:\tools\php72
  - copy php.ini-production php.ini /Y
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_pdo_sqlite.dll >> php.ini
  - echo extension=php_apcu.dll >> php.ini
  - echo memory_limit=1G >> php.ini
  - cd %APPVEYOR_BUILD_FOLDER%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --no-interaction --no-progress --ignore-platform-reqs
  - bin/console doctrine:database:create -n --if-not-exists
  - bin/console doctrine:schema:create -n

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - php vendor\phpspec\phpspec\bin\phpspec
  - php vendor\behat\behat\bin\behat --format=progress --tags='~@postgres'
  - php vendor\phpunit\phpunit\phpunit
